[package]
name = "seal_bid"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/devnet" }

[addresses]
seal_bid = "0x0"
my_coin = "0x0"  # User-defined coin module address
seal_coin = "0x0"  # Seal coin OTW module address
